import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Left_Sidebar from "./Left_Sidebar/page";
import Header from "./Header/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Resilient Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout

  ({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className=" flex w-full">
       
           <div>
             <Left_Sidebar />
           </div>
         
            <div className="flex-1 h-screen overflow-y-auto">
              {children}
            </div>
         
      </body>
    </html>
  );
}
